// 运行时数据GameTemp
var GameTemp = cc.Class.extend({
	ctor : function() {		
		this.map_bgm = null;					// 地图画面 BGM (战斗时记忆用)
		this.message_text = null;				// 信息文章
		this.message_proc = null;				// 信息 返回调用 (Proc)
		this.choice_start = 99;					// 选择项 开始行
		this.choice_max = 0;					// 选择项 项目数
		this.choice_cancel_type = 0;			// 选择项 取消的情况
		this.choice_proc = null;				// 选择项 返回调用 (Proc)
		this.num_input_start = 99;				// 输入数值 开始行
		this.num_input_variable_id = 0;			// 输入数值 变量 ID
		this.num_input_digits_max = 0;			// 输入数值 位数
		this.message_window_showing = false;	// 显示信息窗口
		this.common_event_id = 0;				// 公共事件 ID
		this.in_battle = false;					// 战斗中的标志
		this.battle_calling = false;			// 调用战斗的标志
		this.battle_troop_id = 0;				// 战斗 队伍 ID
		this.battle_can_escape = false;			// 战斗中 允许逃跑 ID
		this.battle_can_lose = false;			// 战斗中 允许失败 ID
		this.battle_proc = null;				// 战斗 返回调用 (Proc)
		this.battle_turn = 0;					// 战斗 回合数
		this.battle_event_flags = {};			// 战斗 事件执行执行完毕的标志
		this.battle_abort = false;				// 战斗 中断标志
		this.battle_main_phase = false;			// 战斗 状态标志
		this.battleback_name = '';				// 战斗背景 文件名
		this.forcing_battler = null;			// 强制行动的战斗者
		this.shop_calling = false;				// 调用商店的标志
		this.shop_id = 0;						// 商店 商品列表
		this.name_calling = false;				// 输入名称 调用标志
		this.name_actor_id = 0;					// 输入名称 角色 ID
		this.name_max_char = 0;					// 输入名称 最大字数
		this.menu_calling = false;				// 菜单 调用标志
		this.menu_beep = false;					// 菜单 SE 演奏标志
		this.save_calling = false;				// 存档 调用标志
		this.debug_calling = false;				// 调试 调用标志
		this.player_transferring = false;		// 主角 场所移动标志
		this.player_new_map_id = 0;				// 主角 移动目标地图 ID
		this.player_new_x = 0;					// 主角 移动目标 X 坐标
		this.player_new_y = 0;					// 主角 移动目标 Y 坐标
		this.player_new_direction = 0;			// 主角 移动目标 朝向
		this.transition_processing = false;		// 过渡处理中标志
		this.transition_name = "";				// 过渡 文件名
		this.gameover = false;					// 游戏结束标志
		this.to_title = false;					// 返回标题画面标志
		this.last_file_index = 0;				// 最后存档的文件编号
		this.debug_top_row = 0;					// 调试画面 保存状态用
		this.debug_index = 0;					// 调试画面 保存状态用
	}
});